AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to schedule a Lambda function using AWS EventBridge (formerly CloudWatch Events)'

Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the Lambda function to trigger
  LambdaFunctionArn:
    Type: String
    Description: ARN of the Lambda function to trigger

Resources:
  # Lambda function is defined from AWS Console
  # https://us-west-1.console.aws.amazon.com/lambda/home?region=us-west-1#/functions

  # Define AWS EventBridge (CloudWatch Events) rule to schedule the Lambda function
  # You can see here: https://us-west-1.console.aws.amazon.com/events/home?region=us-west-1#/eventbus/default/rules/SchedulerEventRule
  SchedulerEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: SchedulerEventRule
      Description: "Schedule Lambda function to run every weekday at 0 AM UTC"
      ScheduleExpression: cron(30 11 ? * MON-FRI *)  # min hour day month day-of-week year
      State: ENABLED
      Targets:
        - Arn: !Ref LambdaFunctionArn
          Id: "LambdaFunctionTarget"

  # Permission for AWS EventBridge to invoke the Lambda function
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SchedulerEventRule.Arn
