name: nikita PyTest Workflow

on:
  push:
    branches:
      - 'nikita*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install pytest
      run: |
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Run pytest
      env:
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.NIKITA_SUPABASE_SERVICE_ROLE_KEY }}
        SUPABASE_URL: ${{ secrets.NIKITA_SUPABASE_URL }}
      run: pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
