name: nikita branch staging deployment

on:
  push:
    branches:
      - 'nikita*'

jobs:
  deploy_lambda:
    name: Publish and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA5ZOUUDPV4JSVHC5U
          aws-secret-access-key: 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
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: List images in Amazon ECR repository
      #   id: list-images
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: fastapi-demo
      #   run: |
      #     images=$(aws ecr list-images --repository-name $ECR_REPOSITORY --registry-id $ECR_REGISTRY --query 'imageIds[*]' --output json)
      #     echo $images > images.json
      
      # - name: Sort images by creation date
      #   id: sort-images
      #   run: |
      #     jq -r 'sort_by(.imagePushedAt)[:-1] | .[]' images.json > old_images.json
      
      # - name: Delete old images from Amazon ECR repository
      #   id: delete-images
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: fastapi-demo
      #   run: |
      #     while IFS=$'\n' read -r image; do
      #       aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --registry-id $ECR_REGISTRY --image-ids imageDigest=$image
      #     done < old_images.json

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fastapi-demo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f ./Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Lambda function with latest ECR image
        env:
          LAMBDA_NAME: lambda-container
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fastapi-demo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws lambda update-function-code \
          --function-name $LAMBDA_NAME \
          --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: Execute Slack Webhook
        if: always()
        run: |
          curl -X POST https://hooks.slack.com/workflows/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